apiVersion: v1
kind: Service
metadata:
  labels:
    name: multicluster-operators-channel
  name: multicluster-operators-channel
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: multicluster-operators-channel
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    name: multicluster-operators-channel
  sessionAffinity: None
  type: ClusterIP
