name: GoPostSubmit

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.21'
  GO_REQUIRED_MIN_VERSION: ''
  GOPATH: '/home/runner/work/multicloud-operators-channel/multicloud-operators-channel/go'
defaults:
  run:
    working-directory: go/src/open-cluster-management.io/multicloud-operators-channel

jobs:
  coverage:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/multicloud-operators-channel
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test
        run: make test
        env:
          KUBECONFIG: /home/runner/.kube/config
      - name: report-coverage
        uses: codecov/codecov-action@v4
        with:
          token: 0718e448-c0d1-4aa1-87dd-6761e6a5a587
          files: /home/runner/work/multicloud-operators-channel/multicloud-operators-channel/go/src/open-cluster-management.io/multicloud-operators-channel/coverage.out
          flags: unit
          name: unit
          verbose: true
          fail_ci_if_error: true

  images:
    name: images
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/multicloud-operators-channel
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: images
        run: make build-images
      - name: push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push quay.io/open-cluster-management/multicloud-operators-channel:latest
